name: servicenow-cpq-landingpage
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: harshajustin/ServiceNow-CPQ-Landingpage
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
  routes:
  - path: /
  run_command: npm run start
  source_dir: /
spec:
  name: servicenow-cpq-landingpage
  region: nyc
